databases:
  - name: movie-twist
    databaseName: movietwist
    user: mysite

services:
  - type: web
    name: movie-twist
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movietwist
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
