default: &default
  adapter: postgresql
  encoding: unicode
  pool:  5

development:
  <<: *default
  database: movies_development

test:
  <<: *default
  database: movies_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
